// The generated `-e` extension compiler — the declarative WIRING half. pi has no native MCP and no
// way to call an `sdk` tool unless an extension registers it (README: "No MCP. …build an extension
// that adds MCP support."). So a node that declares `sdk`/`mcp` tools compiles to a generated pi
// extension that `registerTool`s each one; the bare piNames go on `--tools`. The extension loads via
// explicit `-e` (which survives `--no-extensions`) exactly like the proven providers/coding-plan.ts +
// extensions/node-contract.ts witnesses, whose `defineTool`/`registerTool` shape this mirrors.
//
// Structure is PURE plan → render so the bind-verifier (tools/verify.ts) can cross-check the exact set
// of piNames this binds against what the node declared ("Verified, not trusted", spine philosophy #8).
//
// Robustness: every embedded string/schema goes through JSON.stringify (never naive concat), so a
// description carrying quotes/newlines/backticks can't break — or inject into — the generated source.
// A tool's JSON-Schema `parameters` is wrapped in TypeBox `Type.Unsafe(...)`: pi accepts it as a real
// schema and advertises the correct param shape to the model, without us reconstructing TypeBox by hand.
//
// `execute` routes to the bridge by ADDRESS: `callTool("mcp.github:create_issue", params, …)`. The
// bridge (the deferred MCP/sdk runtime seam) owns the actual transport; this compiler owns the binding.

import type { ToolEntry, ToolSource } from '../types.js';

/** Module the generated extension imports its execute-bridge (`callTool`) from. */
export const DEFAULT_BRIDGE_MODULE = '@piflow/tool-bridge';

/** Compiler knobs. */
export interface CompileOpts {
  /** Module specifier the generated extension imports `callTool` from. Default {@link DEFAULT_BRIDGE_MODULE}. */
  bridgeModule?: string;
}

/** One tool the generated extension will register (the pure plan; builtins are excluded — pi has those natively). */
export interface PlannedTool {
  address: string;
  piName: string;
  source: ToolSource; // 'sdk' | 'mcp'
  description: string;
  label: string;
  /** JSON-Schema object for the tool's args, or undefined (→ an empty object schema). */
  parameters?: unknown;
}

/** A compiled extension: the source pi loads via `-e`, plus the piNames it registers (for bind-verify). */
export interface CompiledExtension {
  /** The pi extension source (TS/JS-compatible). Empty string when there are no non-builtin tools. */
  source: string;
  /** The bare piNames the extension registers — the ground truth the bind-check compares against. */
  registered: string[];
}

/** A readable label from an address: `mcp.github:create_issue` → `github: create_issue`. */
function labelFor(address: string): string {
  return address.replace(/^mcp\./, '').replace(':', ': ');
}

/** Plan which entries become generated tools: drop builtins (pi has them natively), keep sdk/mcp. */
export function planTools(entries: ToolEntry[]): PlannedTool[] {
  return entries
    .filter((e) => e.source !== 'builtin')
    .map((e) => ({
      address: e.address,
      piName: e.piName,
      source: e.source,
      description: e.description,
      label: labelFor(e.address),
      parameters: e.parameters,
    }));
}

/** The schema emitted when a tool declares no parameters (a valid empty-object JSON Schema). */
const EMPTY_SCHEMA = { type: 'object', properties: {} };

/** Render ONE `pi.registerTool({...})` block. Every interpolation is JSON.stringify'd (injection-safe). */
function renderTool(t: PlannedTool): string {
  const params = t.parameters !== undefined ? t.parameters : EMPTY_SCHEMA;
  // promptSnippet/promptGuidelines name the tool explicitly (pi guideline rule) so the model knows when to call it.
  const snippet = `Use ${t.piName} — ${t.description}`;
  const guidelines = [`Call ${t.piName} when the task needs: ${t.description}`];
  return [
    '  pi.registerTool({',
    `    name: ${JSON.stringify(t.piName)},`,
    `    label: ${JSON.stringify(t.label)},`,
    `    description: ${JSON.stringify(t.description)},`,
    `    promptSnippet: ${JSON.stringify(snippet)},`,
    `    promptGuidelines: ${JSON.stringify(guidelines)},`,
    `    parameters: Type.Unsafe(${JSON.stringify(params)}),`,
    '    async execute(toolCallId, params, signal) {',
    `      return callTool(${JSON.stringify(t.address)}, params, { toolCallId, signal });`,
    '    },',
    '  });',
  ].join('\n');
}

/** Render the full pi extension source from a plan. Empty string when there is nothing to bind. */
export function renderExtension(tools: PlannedTool[], opts: CompileOpts = {}): string {
  if (!tools.length) return '';
  const bridge = opts.bridgeModule ?? DEFAULT_BRIDGE_MODULE;
  return [
    '// GENERATED by @piflow/core compileToolExtension — do not edit by hand.',
    '// Binds each declared sdk/mcp tool to the headless pi agent; execute routes through the bridge by address.',
    'import { Type } from "typebox";',
    `import { callTool } from ${JSON.stringify(bridge)};`,
    '',
    'export default function (pi) {',
    tools.map(renderTool).join('\n'),
    '}',
    '',
  ].join('\n');
}

/** Plan + render. Returns the `-e` source and the exact piNames bound (the bind-check ground truth). */
export function compileToolExtension(entries: ToolEntry[], opts: CompileOpts = {}): CompiledExtension {
  const tools = planTools(entries);
  return { source: renderExtension(tools, opts), registered: tools.map((t) => t.piName) };
}
