// GENERATED by deploy/pi-runtime/render-dockerfile.mjs from runtime.mjs — DO NOT EDIT.
// The @piflow/docker backend auto-builds this image on first use; the tag + Dockerfile are the SAME
// single source as the cloud backends (deploy/pi-runtime/runtime.mjs). Bump pi in runtime.mjs, then:
//   node deploy/pi-runtime/render-dockerfile.mjs --write

/** Versioned image tag the local Docker backend builds + boots (pinned to the spec's pi version). */
export const PI_RUNTIME_IMAGE = "piflow-node-runtime:0.80.2";

/** The Dockerfile the backend builds via `docker build -t <tag> -` (no COPY ⇒ empty build context). */
export const PI_RUNTIME_DOCKERFILE = "# GENERATED by deploy/pi-runtime/render-dockerfile.mjs from runtime.mjs — DO NOT EDIT.\n# Bump pi / packages / base in runtime.mjs, then: node deploy/pi-runtime/render-dockerfile.mjs --write\n#\n# piflow \"pi node-runtime\" image — bakes the RUNTIME (one `pi` process per node), NOT the\n# per-node files (the host runner stages those in at run time). Full rationale: runtime.mjs.\n# Local Docker backend (future): `docker build` this image, `docker run` it per run. Same recipe as\n# the cloud images — the whole point of the shared spec.\n\nFROM node:22-trixie-slim\n\nARG PI_VERSION=0.80.2\n\n# One RUN layer so the apt cache never persists in a layer.\nRUN apt-get update \\\n && apt-get install -y --no-install-recommends git ca-certificates ripgrep \\\n && rm -rf /var/lib/apt/lists/* \\\n && npm install -g --ignore-scripts \"@earendil-works/pi-coding-agent@${PI_VERSION}\" \\\n && pi --version\nWORKDIR /home/user\n";
